version: "3"

services:
  postgres:
    image: postgres:11.10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "3306:5432"
    restart: always